### ISSUE TITLE
중계서버 기본 뼈대 구성

### ISSUE THREAD

**Issue by kbu1564** [kbu1564/SecurityBootloader#1]
Linux CentOS 기준으로 중계서버를 구성
C++ 컴파일러사용

Echo Server 형식의 EPOLL 라이브러리를 이용하여 뼈대를 구성할 예정

대략적인 동작 흐름
![2015-07-02 9 01 53](https://cloud.githubusercontent.com/assets/7445459/8476584/add760c4-20fd-11e5-82a5-6f972e4c0867.png)

**Comment by KangHoyong** [comment]
중간 서버 구성 기본 뼈대 확인하고 갑니다

**Comment by yunheur** [comment]
확인 했습니다.
