### ISSUE TITLE
git branch 이름 통일 문제

### ISSUE THREAD

**Issue by kbu1564** [kbu1564/SecurityBootloader#13]
현재 `feature-network` 브렌치가 브렌치명의 규칙에 알맞지 않은 이름으로 되어있으므로
해당 브렌치 이름 정정 혹은 불필요시 pull request 요청올리고 합쳐친 뒤 제거해 주는 작업이 필요함
![1](https://cloud.githubusercontent.com/assets/7445459/9160200/214bafc4-3f71-11e5-8419-c0485cdb4a58.JPG)

@formfoxk 

기능 추가에 대한 브렌치 명은 무조건 `feature/기능명` 이런 방식으로 명명하여 브렌치 생성할 것
기능명의 경우 띄어쓰기 대신 단어의

첫문자를 대문자로 나머지는 소문자로 하며 영문자 소.대문자, 숫자 이외의 것은 사용금지
자세한것은 SourceTree 사용 참고

**Comment by GangHoyong** [comment]
:+1:  확인했습니다

**Comment by yunheur** [comment]
넵 확인 했습니다.

**Comment by kbu1564** [comment]
이 문제도 해결됨 이슈를 닫음
