### ISSUE TITLE
README.md 파일의 양식 꾸미는 작업이 필요

### ISSUE THREAD

**Issue by kbu1564** [kbu1564/SecurityBootloader#16]
해당 이슈는 금주 첫번째 회의때 정하여 구성하는 것으로 계획중
@GangHoyong @formfoxk @kimhajin

**Comment by KangHoyong** [comment]
README.md 파일 꾸민후 그 꾸민 문장을 Wiki 첫 페이지로 쓰면 될거같습니다..!!

**Comment by kbu1564** [comment]
작업 완료로 인한 이슈 종료
