### ISSUE TITLE
Android development

### ISSUE THREAD

**Issue by kimhajin** [kbu1564/SecurityBootloader#17]
## 1. APP Design
- 내부 UI Design (기본골격 디자인)
  
  <img width="784" alt="2015-08-11 4 00 48" src="https://cloud.githubusercontent.com/assets/13030433/9196411/21bbe640-4066-11e5-9040-e0f6c58e49e5.png">

<기본동작>  설명
Boot 버튼 클릭시 팝업창 띄우고 "booting Start" 문구와 YES / NO 선택
YES 선택시 : boot실시 / NO 선택시 : 취소 
YES 부가기능 "boot" 단어를 중계서버에 넘겨준다..

Cancel 버튼 클릭시 팝업창 띄우고 "Shutdown" 문구와  YES /  NO 선택
YES 선택시 : Shutdown 실시 / NO 선택시 : 취소 
YES 부가기능  "Shutdown" 단어를 중계서버에 넘겨준다..

사진뷰 (기본기능) : 웹캠 화면을 보여주는  기능 
## 2.  APP Splash  Design
- 홈버튼 누를후 다시 어플 실행시 Splash는 작동하지 않습니다 !! (처음 시작과 종료후 다시 시작시만 실행)
- Splash Design
- 규격 : 480 \* 800 hdpi / 720 \* 1280 xhdpi 
  
  ![loading](https://cloud.githubusercontent.com/assets/9815703/9321451/a176bb68-45a1-11e5-9c9c-c33f396da0ac.jpg)
## Icon Design
- 파일형식 : PNG 
- 관련 사이트 http://www.iconarchive.com/
- 관련 사이트 http://makeappicon.com/download/e7635e8a5ef84dcfb65f0e0a900f40e5
  - 사진을 넣으면 아이콘 으로 변환 해주는 자동 프로그램 !! 
- Icon Design
  ![images](https://cloud.githubusercontent.com/assets/13030433/9196413/21d9e762-4066-11e5-81f2-8e2ab583245f.jpeg)
## 버튼 클릭시 팝업창 띄우기

[버튼 팝업창 참고사이트](http://blog.naver.com/androidshin/220199182664)
- 클릭할 버튼
  
  <img width="225" alt="default" src="https://cloud.githubusercontent.com/assets/13030433/9292689/b336b2c8-4442-11e5-8540-865a9ca78fc1.png">
- Shutdown 클릭시 팝업창
  
  <img width="197" alt="shutdown" src="https://cloud.githubusercontent.com/assets/13030433/9292692/e1e2eee8-4442-11e5-8791-095d31247766.png">
- Start 클릭시 팝업창
  
  <img width="198" alt="1" src="https://cloud.githubusercontent.com/assets/13030433/9292696/f4428eea-4442-11e5-8608-f11e5eda547f.png">
## 어플에서 백그라운드 실행 상태

서비스 시작되는거 확인 ! 
  <img width="804" alt="2015-08-17 11 10 07" src="https://cloud.githubusercontent.com/assets/9815703/9321414/10756a9c-45a1-11e5-82b0-e97ae3251e64.png">

실제로 구동중인 어플 확인결과 !! 백그라운드 서비스 실행중인거 확인!!
  <img width="471" alt="2015-08-17 10 45 26" src="https://cloud.githubusercontent.com/assets/9815703/9321413/1072aec4-45a1-11e5-9364-b2eeb304131c.png">
## 안드로이드 구글 지도 API 및 지도 카메라 이동, 줌
1. 마크 클릭시 : sample Marker
2. 위도 경도를 이용하여 마크 표시 카메라 이동 및 줌 표시 

결과 화면 (구글맵  V2 버전부터는 실제 안드로이드 디바이스에서만 가능)

  ![kakaotalk_photo_2015-08-21-00-23-52](https://cloud.githubusercontent.com/assets/9815703/9387356/1cd90018-479b-11e5-9075-ea3f41b788cb.jpeg)
## Android 개발 관련 참고 사이트

[Splash Design 참고 자료](http://blog.naver.com/hswalter/220242327124)

[백그라운드 관련 참고자료](http://webnautes.tistory.com/668)

[백그라운드 관련 참고자료](http://blog.naver.com/cestlavie_01/40188369345)

[Activity 생명주기 관련 참고 사이트](http://mydevromance.tistory.com/archive/20120112#recentComments)

[Android 구글 개발 센터](https://developers.google.com/android/reference/com/google/android/gms/package-summary)

[다지인 참고자료](https://www.google.com/design/spec/style/icons.html#)

[구글 지도 API 참고 사이트](http://www.androidpub.com/2398318)

[카메라 줌 레벨 수정 방법 참고 사이트](http://stackoverflow.com/questions/16998169/google-maps-v2-set-zoom-level)

**Comment by kbu1564** [comment]
![1](https://cloud.githubusercontent.com/assets/7445459/9194605/6c761ca0-4057-11e5-810b-d633e2c81c90.JPG)

위의 사진에서의 빨간 동그라미 부분을 누르게 되면 파일 업로드 창이 뜸
해당 기능을 통해 이미지 업로드 부탁함

@kimhajin 
**사진뷰 (기본기능) : 웹캠 화면을 보여주는 기능**

이 문구 부분의 사진뷰 부분의 이미지는 어떤 컨텐츠가 들어가면 좋을지에 대한것을 추후 회의를 거쳐
입력할 예정 - 아마 아이피 주소를 통한 현재 위치 지도가 들어갈 것 같음. 해당 부분의 경우 naver 지도 api 를 이용하면 쉽게 지도 연동이 가능

**Comment by KangHoyong** [comment]
사진 파일 업로드 해서 수정했습니다

**Comment by kbu1564** [comment]
@GangHoyong @kimhajin 확인했고 저대로 계속 진행해 주면 될것 같음 :+1:

**Comment by KangHoyong** [comment]
### Splash Design 최종 수정

<img width="401" alt="2015-08-13 6 23 04" src="https://cloud.githubusercontent.com/assets/9815703/9246720/6672386a-41e8-11e5-8e0e-a609b7df8627.png">

**Comment by KangHoyong** [comment]
## 버튼 부분 디자인 수정
- 팝업창 경고 아이콘 추가, 팝업창 경고 문구 추가
  
  <img width="418" alt="2015-08-17 3 02 38" src="https://cloud.githubusercontent.com/assets/9815703/9298888/540e7ff6-44f1-11e5-845a-ae2700a775ff.png"> 
  
  <img width="418" alt="2015-08-17 3 02 57" src="https://cloud.githubusercontent.com/assets/9815703/9298889/540f57aa-44f1-11e5-8dee-c61dea043848.png">

**Comment by GangHoyong** [comment]
## 안드로이드 구글 지도 API 및 지도 카메라 이동, 줌 

1. (구글 지도 API) 참고 사이트 : http://www.androidpub.com/2398318
2. 카메라 줌 레벨 수정 방법 참고 사이트 : http://www.androidpub.com/2398318
3. 마크 클릭시 : sample Marker

결과 화면 (구글맵  V2 버전부터는 실제 안드로이드 디바이스에서만 가능)

  ![kakaotalk_photo_2015-08-21-00-23-52](https://cloud.githubusercontent.com/assets/9815703/9387356/1cd90018-479b-11e5-9075-ea3f41b788cb.jpeg)
