### ISSUE TITLE
device is busy 나오는 경우 해결 방법

### ISSUE THREAD

**Issue by KangHoyong** [kbu1564/SecurityBootloader#5]
- device is busy 나오는 경우 해결법

```
누군가 mount 되어있는 것을 쓰고 있다는 것이므로 강제로 쓰고 있는 것을 멈춰야한다 . 
이문제를 해결방법은
fuser -mk /AAA
/AAA : mount 되어있는 폴더 
```

또 다른 방법은 다른 loop1사용하면됩니다 !!
다른 loop(0~4)를 사용하는것을 추천합니다!
- 디스크 삭제 방법 

```
sudo mkfs.ext2 brdisk-img.raw 
```

더 좋은 방법이 생길경우 댓글달아주시면 수정반영하겠습니다!!

**Comment by kbu1564** [comment]
1안과 같이 강제로 멈추는 방법은 피하고 되도록이면 아래의 loop1을 사용하는 방식이 더 안전할듯

**Comment by KangHoyong** [comment]
:+1:
