### ISSUE TITLE
Linux Boot Loader Grub 설정 관련 사항 추가 내용 

### ISSUE THREAD

**Issue by KangHoyong** [kbu1564/SecurityBootloader#6]
## 
#4 설정 관련 사항 추가
## 
- default = 엔트리번호 : 기본값으로 부팅 되도록 설정되어진 순서
  GRUB 초기 부팅화면에서 부팅할 메뉴를 선택하지 않았을 경우 사용할 기본 부팅메뉴를 선택해둔 
  것입니다.
  각 메뉴의 번호는 0번부터 시작해서 첫 번째 부팅메뉴가 0번이고 두 번째 부팅 메뉴가 1번 순서로 
   지정하면 됩니다.
- timeout = 부팅시간(초) : timeout 에 지정된 시간에 0번째 부팅메뉴를 실행
  GRUB 초기부팅화면에서 지체하는 시간을 초단위로 설정한 값입니다.
  부팅 초기화면에서 부팅메뉴를 선택하는데 이때의 대기시간을 초단위로 설정한 값으로 이 시간이 경과하는 동안에 선택되지 않는다면 기본 부팅메뉴로 부팅이 진행됩니다.
- splashimage (장치명,파티션) 이미지파일
  GRUB 부팅 화면에 나타나는 배경 이미지를 설정해놓은 것입니다.
  초기화면에서 GRUB 의 배경이미지를 변경하려면 이 파일명을 다른 이미지파일의 경로로 넣어주
  됩니다.
- 기본설정은 (hd0,0) 위치에 있는 /grub/splash.xpm.gz 이미지 파일을 사용 하고있습니다.
- password
  부팅시 GRUB 모드로 들어가기 위한 암호화된 패스워드입니다.
  password항목이 존재하지 않는다면 패스워드 없이 GRUB 모드로 진입가능합니다.
- title 부팅제목
  GRUB 부팅화면의 메뉴에 나타나는 제목 리눅스로 부팅하기 위한 옵션입니다.
  title DOS
  윈도우로 부팅하기 위한 옵션입니다.
  root (하드,파티션)
  리눅스의 루트(/) 파티션의 위치를 지정합니다.
  kernel /vmlinuz-버전 ro root=/dev/장치명
  부팅할 경우에 메모리로 로드할 kernel 의 이미지를 지정해놓은 것으로
  ro root 는 루트파티션의 위치로 부팅이 되지 않을 경우 강제로 루트파티션을 지정해줄 수 있습니다.
  initrd
  SCSI 디스크를 사용하는 경우에는 반드시 지정해야 하는 항목으로 해당 메뉴로 부팅할 때 사용할 initrd
  이미지를 지정해주는 것 입니다.
  initrd /initrd-x.x.x-x.el5.img 의 의미는 initrd 로 사용할 이미지 파일을 /initrd-x.x.x-x.el5.img로 지정한것이다.
  initrd 이미지 파일명 : 시스템 초기화용 램 디스크 이미지 파일
  initrd /initramfs-2.6................img 초기화를 담당하는 이미지 파일의 경로를 지정하는 옵션이다.
  rootnoverify (hd0, 0)
  rootnoverify 옵션은 리눅스 타이틀의 root 옵션과 비슷한 기능을 하지만 리눅스와 달리 해당 파티션을 마운트 하지 않는다.
  GRUB 이 인식할수 없는 파티션 (ntfs nt 등) 에서는 부팅 권한만 넘겨줍니다.
- fallback = 엔트리번호 : 부팅 실패시 다음 순위 부팅순서
- default 항목에서 설정한 기본 부팅메뉴로 부팅되지 않았을 경우 다음으로 부팅할 부팅항목을 설정 해줍니다.
- chainloder+1
  chainloder 옵션을 이용하여 다른 부트로더로 제어권을 넘깁니다.
  윈도우와 리눅스를 멀티부팅 하면 이 옵션을 통해서 윈도우의 부트로더인 NTLDR에 의해 윈도우가 부팅 됩니다.

---

Grub 관련 내용 참고 사이트 및 출저 :  [Grub참고사이트](http://121202.tistory.com/60)

**Comment by kbu1564** [comment]
실제로 set 다음에 오게되는 set default=0" 등의 값들은 grub_get_env 등의 내부 함수를 이용하여 값을 가져오는 과정을 거침

#3 이슈를 참고할것

**Comment by kbu1564** [comment]
관련 이슈는 1차 중간평가때 구현됨
이슈를 닫음
